### ISSUE TITLE
Consider adding TSP

### ISSUE THREAD

**Issue by tpoindex** [dbohdan/compilers-targeting-c#41]
Hi,
You might want to consider adding my TSP project as an open source compile-to-C compiler.  TSP  targets a subset of Tcl.  Currently, it compiles to C (or Java), and to a loadable Tcl module on the fly.  If this doesn't meet your criteria, feel free to cancel this issue.
https://github.com/tpoindex/tsp

**Comment by dbohdan** [comment]
Heya. I've tried TSP before. I'll add it.

A question about how to describe it: I've noticed that you do not call TSP a JIT in the documentation. Is there a reason for it? TSP looks awfully like a JIT to me. :-)

**Comment by tpoindex** [comment]
I intended TSP to be a both a AOT compiler, where modules could be saved in
compiled form, but you're right, in it's current form, it's more of a JIT.
I consider that to be a function of the compiler driver, which currently
loads the compiled modules right away.   Hopefully someday I'll get back to
working on it.

**Comment by dbohdan** [comment]
Got it. I'll call TSP a JIT in the description. I hope you get an opportunity to work on it again. AOT or not, I think TSP has potential as an alternative to plain Critcl; I'm generally fond of the idea of extending Tcl for performance in a memory-safe language instead of C. (I have experments in that direction, [my favorite one](https://wiki.tcl-lang.org/48819) involving LuaJIT. At one point I toyed with the idea of compiling Tcl to Lua to leverage LuaJIT.)

I added TSP in abd311c.
