### ISSUE TITLE
Is this repository maintained?

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [dbohdan/compilers-targeting-c#77]
@dbohdan It has been a while since you've updated this repository. I know you're from Ukraine and I really hope you're safe and ok. If you need a help with maintaining this repo let me know.

**Comment by jpgpng** [comment]
I don't think so.

**Comment by DanielMazurkiewicz** [comment]
@dbohdan @jpgpng  if there will be no response till next weekend, I'll for it and apply all the requested changes

**Comment by dbohdan** [comment]
@DanielMazurkiewicz Sorry for the delay! And I appreciate the wishes. Unfortunately, right now I am not OK. I am quite ill and stuck in [redacted] near the eastern border. I have just recently begun to recover from my illness. I am not going to work on my repos for a while.

If you are interested in maintaining this repo, I can give you commit access. I have wanted someone to hand it over to for a while.  Since we haven't worked together, it'll be as a trial at first. My requirements are that you

1. Check that the compilers you add actually exist, work to some extent (can you write "99 bottles"?), target C or C++, and are open source. 
2. Try to write useful notes for every compiler you add. (It was my mistake not to do it for all compilers from the start.) The notes must focus on the objective characteristics. No marketing language like "groundbreaking" or vague claims like "fast". ("The fastest for language X" is good.) If a PR that meets 1. has notes written like this, merge the PR then rewrite the notes.

If this sounds good, tell me, and I'll add you as a collaborator.

**Comment by DanielMazurkiewicz** [comment]
@dbohdan 

No problems at all with the delay. Glad to hear from you, hope you will recover quickly and get back on your feet.

As for the requirements, the idea of writing some example code like "99 bottles" for every language is very cool, but unfortunately I don't think I have that much of time to play with all these languages around. Been playing with many and just setting things up can be very time consuming. All I can promise you is going once in a while through PRs and issues and maintaining list by following your current patterns.

**Comment by dbohdan** [comment]
> Glad to hear from you, hope you will recover quickly and get back on your feet.

Thanks! 

> the idea of writing some example code like "99 bottles" for every language is very cool, but unfortunately I don't think I have that much of time to play with all these languages around.

Sorry, I wasn't very clear. I didn't mean that you should personally write "99 bottles" in each new language (I don't do that), just see that it is possible to write a simple program. I usually do it by looking at the language's code examples and tests.

> All I can promise you is going once in a while through PRs and issues and maintaining list by following your current patterns.

Yeah, this is fine. I am not asking you to do more than I did with language testing. Thank you for volunteering to help. I have invited you to join as a collaborator.
